version: '3.8'
services:
  db:
    build: .
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=authuser
      - DB_PASSWORD=authpassword
      - DB_NAME=authdb
      - JWT_SECRET=your_jwt_secret

volumes:
  postgres_data:
